import {
  FlowDefinition, FlowNode, AiNode, AgentNode, BranchNode,
  LoopNode, ParallelNode, HttpNode, MemoryNode, WaitNode, SleepNode, CodeNode,
} from "./types.js";

// ─── Cloudflare Workflows Transpiler ──────────────────────────────────────────
// Converts an openclaw-flow definition into a Cloudflare WorkflowEntrypoint
// TypeScript class. This is the "write once, run anywhere" bridge.
//
// Each node type maps to a Cloudflare Workflows primitive:
//
//   do: ai       → step.do(name, async () => { ... AI call ... })
//   do: agent    → step.do(name, async () => { ... AI call ... })
//   do: branch   → JS if/else (control flow, no step needed)
//   do: loop     → for...of loop wrapping step.do
//   do: parallel → Promise.all([ step.do, step.do, ... ])
//   do: http     → step.do(name, async () => { fetch(...) })
//   do: memory   → step.do(name, async () => { KV read/write })
//   do: wait     → step.waitForEvent(name, { type, timeout })
//   do: sleep    → step.sleep(name, duration)
//   do: code     → inline JS expression (no step wrapper needed)

export function transpileToCloudflare(flow: FlowDefinition): string {
  const className = toPascalCase(flow.flow);
  const nodeCode = flow.nodes.map((n) => transpileNode(n, 2)).join("\n\n");

  return `// Generated by openclaw-flow transpiler
// Source flow: ${flow.flow}${flow.description ? `\n// ${flow.description}` : ""}
// To deploy: wrangler deploy

import { WorkflowEntrypoint, WorkflowStep, WorkflowEvent } from "cloudflare:workers";

type Env = {
  // Add your Cloudflare bindings here (KV, R2, AI, etc.)
  [key: string]: unknown;
};

type Params = {
  // Matches the trigger input shape for this flow
  [key: string]: unknown;
};

export class ${className} extends WorkflowEntrypoint<Env, Params> {
  async run(event: WorkflowEvent<Params>, step: WorkflowStep) {
    // Flow state — equivalent to openclaw-flow's FlowState
    const state: Record<string, unknown> = { trigger: event.payload };

${nodeCode}

    return state;
  }
}
`;
}

// ─── Per-node transpilation ───────────────────────────────────────────────────

function transpileNode(node: FlowNode, indent: number): string {
  const pad = " ".repeat(indent);
  const retryConfig = node.retry
    ? `, { retries: { limit: ${node.retry.limit}, delay: "${node.retry.delay}"${node.retry.backoff ? `, backoff: "${node.retry.backoff}"` : ""} }${node.timeout ? `, timeout: "${node.timeout}"` : ""} }`
    : (node.timeout ? `, { timeout: "${node.timeout}" }` : "");

  switch (node.do) {

    case "ai":
    case "agent": {
      const n = node as AiNode | AgentNode;
      const inputRef = n.input ? `resolveTemplate(state, "${n.input}")` : "undefined";
      const prompt = "prompt" in n ? n.prompt : (n as AgentNode).task;
      const outputLine = n.output ? `\n${pad}state["${n.output}"] = ${camel(node.name)};` : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}"${retryConfig}, async () => {
${pad}  const input = ${inputRef};
${pad}  const prompt = resolveTemplate(state, ${JSON.stringify(prompt)});
${pad}  // Call your AI provider here (Workers AI, Anthropic, OpenAI, etc.)
${pad}  // Example with Workers AI:
${pad}  // const result = await env.AI.run("@cf/anthropic/claude-3-haiku", { prompt });
${pad}  throw new Error("Configure your AI provider binding in this step");
${pad}});${outputLine}`;
    }

    case "branch": {
      const n = node as BranchNode;
      const paths = Object.entries(n.paths)
        .map(([val, target]) => `${pad}  if (String(state["${n.on.split(".")[0]}"]?.${n.on.split(".").slice(1).join("?.")}) === "${val}") { /* jump to ${target} — refactor as function */ }`)
        .join("\n");
      const defaultLine = n.default ? `\n${pad}  // else: ${n.default}` : "";
      return `${pad}// branch: ${node.name}\n${paths}${defaultLine}
${pad}// Note: Cloudflare Workflows don't support goto. Extract branched nodes into
${pad}// separate methods or restructure using if/else blocks.`;
    }

    case "loop": {
      const n = node as LoopNode;
      const innerCode = n.nodes.map((inner) => transpileNode(inner, indent + 2)).join("\n");
      const outputLine = n.output ? `\n${pad}state["${n.output}"] = ${camel(node.name)}Results;` : "";
      return `${pad}const ${camel(node.name)}Results: unknown[] = [];
${pad}for (const ${n.as} of (state["${n.over.split(".")[0]}"] as unknown[]) ?? []) {
${pad}  // Loop iteration: ${node.name}
${innerCode}
${pad}  ${camel(node.name)}Results.push(${n.as});
${pad}}${outputLine}`;
    }

    case "parallel": {
      const n = node as ParallelNode;
      const branches = n.nodes
        .map((inner) =>
          `    step.do("${inner.name}"${retryConfig}, async () => {\n      // ${inner.do} node: ${inner.name}\n      throw new Error("Implement ${inner.name}");\n    })`,
        )
        .join(",\n");
      const fn = n.mode === "race" ? "Promise.race" : "Promise.all";
      const outputLine = n.output ? `\n${pad}state["${n.output}"] = ${camel(node.name)};` : "";
      return `${pad}const ${camel(node.name)} = await ${fn}([\n${branches}\n${pad}]);${outputLine}`;
    }

    case "http": {
      const n = node as HttpNode;
      const outputLine = n.output ? `\n${pad}state["${n.output}"] = ${camel(node.name)};` : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}"${retryConfig}, async () => {
${pad}  const url = resolveTemplate(state, ${JSON.stringify(n.url)});
${pad}  const resp = await fetch(url, {
${pad}    method: ${JSON.stringify(n.method ?? "GET")},
${pad}    headers: { "Content-Type": "application/json"${n.headers ? `, ...${JSON.stringify(n.headers)}` : ""} },
${pad}    ${n.body ? `body: resolveTemplate(state, ${JSON.stringify(typeof n.body === "string" ? n.body : JSON.stringify(n.body))})` : ""},
${pad}  });
${pad}  return resp.json();
${pad}});${outputLine}`;
    }

    case "memory": {
      const n = node as MemoryNode;
      const outputLine = n.output ? `\n${pad}state["${n.output}"] = ${camel(node.name)};` : "";
      return `${pad}const ${camel(node.name)} = await step.do("${node.name}", async () => {
${pad}  const key = resolveTemplate(state, ${JSON.stringify(n.key)});
${pad}  // Use env.KV (Cloudflare KV) or env.DB (D1) for persistence
${pad}  ${n.action === "write"
    ? `await env.KV.put(key, JSON.stringify(${n.value ? `resolveTemplate(state, ${JSON.stringify(n.value)})` : "null"}));`
    : n.action === "delete"
    ? `await env.KV.delete(key);`
    : `return JSON.parse(await env.KV.get(key) ?? "null");`}
${pad}});${outputLine}`;
    }

    case "wait": {
      const n = node as WaitNode;
      if (n.for === "approval") {
        return `${pad}// wait: approval gate — "${node.name}"
${pad}// In Cloudflare: send an event from your UI/webhook to resume
${pad}const ${camel(node.name)} = await step.waitForEvent("${node.name}", {
${pad}  type: "approval",
${pad}  timeout: "${n.timeout ?? "24 hours"}",
${pad});`;
      }
      return `${pad}const ${camel(node.name)} = await step.waitForEvent("${node.name}", {
${pad}  type: ${JSON.stringify(n.event ?? "event")},
${pad}  timeout: "${n.timeout ?? "24 hours"}",
${pad}});
${n.output ? `${pad}state["${n.output}"] = ${camel(node.name)};` : ""}`;
    }

    case "sleep": {
      const n = node as SleepNode;
      return `${pad}await step.sleep("${node.name}", "${n.duration}");`;
    }

    case "code": {
      const n = node as CodeNode;
      const inputExpr = n.input ? `state["${n.input.split(".")[0]}"]` : "undefined";
      const outputLine = n.output ? `\n${pad}state["${n.output}"] = ${camel(node.name)};` : "";
      return `${pad}const ${camel(node.name)} = (() => {
${pad}  const input = ${inputExpr};
${pad}  return (${n.run});
${pad}})();${outputLine}`;
    }

    default:
      return `${pad}// Unknown node type: ${(node as FlowNode).do}`;
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toPascalCase(s: string): string {
  return s.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase())
    .replace(/^(.)/, (_, c: string) => c.toUpperCase()) + "Workflow";
}

function camel(s: string): string {
  return s.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
}

// Emitted as a helper function in the generated file
const _resolveTemplateHelper = `
// Template resolver — injected by transpiler
function resolveTemplate(state: Record<string, unknown>, template: string): string {
  return template.replace(/\\{\\{\\s*([\\w.]+)\\s*\\}\\}/g, (_, path) => {
    const val = path.split(".").reduce((o: unknown, k: string) =>
      o != null && typeof o === "object" ? (o as Record<string, unknown>)[k] : undefined, state);
    return val === undefined ? \`{{\${path}}}\` : typeof val === "object" ? JSON.stringify(val) : String(val);
  });
}`;
